[project]
name = "jax-growing-ncas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "equinox>=0.13.0",
    "jax>=0.6.2",
    "matplotlib>=3.10.3",
    "optax>=0.2.5",
    "requests>=2.32.4",
    "torch>=2.7.1",
]
